version: "3.5"
volumes:
  nextcloud:
  apps:
  db:
  config:

services:
  frontend:
    image: acatonl/woo-ui-develop
    ports:
    - "8081:80"

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='!ChangeMe!'
      - MYSQL_PASSWORD='!ChangeMe!'
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      
  nextcloud:
    user: root
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html:rw
      - ./custom-apps:/var/www/html/custom_apps
      - .:/var/www/html/custom_apps/larpingapp
      - .:/var/www/html/custom_apps/opencatalogi
    environment:
      - MYSQL_PASSWORD='!ChangeMe!'
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - TZ=Europe/Amsterdam
